%% Visualize_Spectra
% Make plots of all the earthquake spectra generated by this set of
% calculations
cmappp=turbo(length(Mrrlist))
% loop over mode number
for currN = 0:MaxN
% loop over events
for evnum = 1:length(Mrrlist)
 info = load(['Event_' num2str(evnum) modename 'AmpSpectra.txt']);
idx =find(info(1,:) == currN);
subset = info(2:end,idx)
currperiods = subset(:,1);
curramp =  subset(:,2);
figure(currN+1)
plot(currperiods,curramp./max(curramp),'linewidth',2,'color',cmappp(evnum,:))
hold on
currstr = ['Depth = ' num2str(Depthlist(evnum))];
StrList{evnum} = currstr;
end
legend(StrList)
end